//! Generate a fastviz TOML config from a set of selected topics.
//!
//! The UI's topic discoverer uses this to materialise the user's checkbox
//! selection into a runnable `--config` file. Topics whose message types
//! fastviz does not understand are silently dropped.

use scene::SceneGraph;

use crate::subscribers::{laserscan, marker, occupancy, path, pointcloud, pose};

/// Snapshot of the orbit camera, baked into `[view]` so a saved config reopens
/// with the same framing (RViz saves the camera the same way). Mirrors the
/// fields of `renderer::OrbitCamera` that the UI controls.
#[derive(Clone, Copy, Debug)]
pub struct CameraSave {
    pub target: [f32; 3],
    pub yaw: f32,
    pub pitch: f32,
    pub distance: f32,
}

/// Plain-data representation of a UI group passed in for saving. Decouples the
/// writer from the egui-dependent runtime type in the app crate.
#[derive(Clone, Debug)]
pub struct UiGroupSave {
    pub name: String,
    pub topics: Vec<String>,
    pub urdf: bool,
    pub tf: bool,
    pub collapsed: bool,
}

/// Top-level kinds the writer can emit. Anything not in this set is ignored.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum TopicKind {
    Map,
    Pose,
    PoseArray,
    Path,
    Scan,
    PointCloud,
    Marker,
    MarkerArray,
}

impl TopicKind {
    /// First supported kind that matches one of `types`.
    pub fn from_types(types: &[String]) -> Option<Self> {
        types.iter().find_map(|t| Self::from_type(t))
    }

    pub fn from_type(ty: &str) -> Option<Self> {
        match ty {
            occupancy::MSG_TYPE => Some(Self::Map),
            pose::STAMPED_TYPE => Some(Self::Pose),
            pose::ARRAY_TYPE => Some(Self::PoseArray),
            path::MSG_TYPE => Some(Self::Path),
            laserscan::MSG_TYPE => Some(Self::Scan),
            pointcloud::MSG_TYPE => Some(Self::PointCloud),
            marker::MARKER_TYPE => Some(Self::Marker),
            marker::ARRAY_TYPE => Some(Self::MarkerArray),
            _ => None,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::Map => "OccupancyGrid",
            Self::Pose => "PoseStamped",
            Self::PoseArray => "PoseArray",
            Self::Path => "Path",
            Self::Scan => "LaserScan",
            Self::PointCloud => "PointCloud2",
            Self::Marker => "Marker",
            Self::MarkerArray => "MarkerArray",
        }
    }
}

/// Render selected topics into a fastviz TOML config string.
///
/// `topics` is the (topic, types) snapshot. `selected` lists the topic names
/// the user checked. Topics whose message type isn't supported are skipped.
/// `reference_frame` is written verbatim as the file's `reference_frame`.
pub fn to_toml(
    topics: &[(String, Vec<String>)],
    selected: &[String],
    reference_frame: &str,
) -> String {
    use std::collections::BTreeSet;
    let want: BTreeSet<&str> = selected.iter().map(String::as_str).collect();

    let mut map: Option<String> = None;
    let mut poses: Vec<String> = Vec::new();
    let mut pose_arrays: Vec<String> = Vec::new();
    let mut paths: Vec<String> = Vec::new();
    let mut scans: Vec<String> = Vec::new();
    let mut points: Vec<String> = Vec::new();
    let mut markers: Vec<String> = Vec::new();
    let mut marker_arrays: Vec<String> = Vec::new();

    for (topic, types) in topics {
        if !want.contains(topic.as_str()) {
            continue;
        }
        match TopicKind::from_types(types) {
            Some(TopicKind::Map) => {
                // First selected map wins — fastviz only displays one.
                if map.is_none() {
                    map = Some(topic.clone());
                }
            }
            Some(TopicKind::Pose) => poses.push(topic.clone()),
            Some(TopicKind::PoseArray) => pose_arrays.push(topic.clone()),
            Some(TopicKind::Path) => paths.push(topic.clone()),
            Some(TopicKind::Scan) => scans.push(topic.clone()),
            Some(TopicKind::PointCloud) => points.push(topic.clone()),
            Some(TopicKind::Marker) => markers.push(topic.clone()),
            Some(TopicKind::MarkerArray) => marker_arrays.push(topic.clone()),
            None => {}
        }
    }

    let mut out = String::new();
    out.push_str("# fastviz config — generated by the topic discoverer.\n");
    out.push_str(&format!("reference_frame = \"{reference_frame}\"\n\n"));

    if let Some(t) = &map {
        out.push_str("[map]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string(t)));
    }
    if !poses.is_empty() {
        out.push_str("[poses]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&poses)));
    }
    if !pose_arrays.is_empty() {
        out.push_str("[pose_arrays]\n");
        out.push_str(&format!(
            "topics = [{}]\n\n",
            toml_string_list(&pose_arrays)
        ));
    }
    if !paths.is_empty() {
        out.push_str("[paths]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&paths)));
    }
    if !scans.is_empty() {
        out.push_str("[scans]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&scans)));
    }
    if !points.is_empty() {
        out.push_str("[points]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&points)));
    }
    if !markers.is_empty() {
        out.push_str("[markers]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&markers)));
    }
    if !marker_arrays.is_empty() {
        out.push_str("[marker_arrays]\n");
        out.push_str(&format!(
            "topics = [{}]\n\n",
            toml_string_list(&marker_arrays)
        ));
    }
    out
}

/// Like [`to_toml`] but also bakes the live view state into the saved file:
/// - the current per-kind style colors / sizes are read from the matching
///   entity in `scene` (first matched topic wins for a given kind)
/// - the TF axis length is written into `[tf]`
/// - UI groups are emitted in the order they appear in `ui_groups`
///
/// Topics not represented in `scene` fall back to the writer's default styles.
#[allow(clippy::too_many_arguments)]
pub fn to_toml_full(
    topics: &[(String, Vec<String>)],
    selected: &[String],
    reference_frame: &str,
    scene: &SceneGraph,
    tf_axis_length: f32,
    ui_groups: &[UiGroupSave],
    camera: Option<CameraSave>,
) -> String {
    use std::collections::BTreeSet;
    let want: BTreeSet<&str> = selected.iter().map(String::as_str).collect();

    let mut map: Option<String> = None;
    let mut poses: Vec<String> = Vec::new();
    let mut pose_arrays: Vec<String> = Vec::new();
    let mut paths: Vec<String> = Vec::new();
    let mut scans: Vec<String> = Vec::new();
    let mut points: Vec<String> = Vec::new();
    let mut markers: Vec<String> = Vec::new();
    let mut marker_arrays: Vec<String> = Vec::new();

    for (topic, types) in topics {
        if !want.contains(topic.as_str()) {
            continue;
        }
        match TopicKind::from_types(types) {
            Some(TopicKind::Map) => {
                if map.is_none() {
                    map = Some(topic.clone());
                }
            }
            Some(TopicKind::Pose) => poses.push(topic.clone()),
            Some(TopicKind::PoseArray) => pose_arrays.push(topic.clone()),
            Some(TopicKind::Path) => paths.push(topic.clone()),
            Some(TopicKind::Scan) => scans.push(topic.clone()),
            Some(TopicKind::PointCloud) => points.push(topic.clone()),
            Some(TopicKind::Marker) => markers.push(topic.clone()),
            Some(TopicKind::MarkerArray) => marker_arrays.push(topic.clone()),
            None => {}
        }
    }

    let mut out = String::new();
    out.push_str("# fastviz config — generated by Save current config.\n");
    out.push_str(&format!("reference_frame = \"{reference_frame}\"\n\n"));

    out.push_str("[tf]\n");
    out.push_str(&format!("axis_length = {}\n\n", fmt_f(tf_axis_length)));

    if let Some(c) = camera {
        out.push_str("[view]\n");
        out.push_str(&format!(
            "target = [{}, {}, {}]\n",
            fmt_f(c.target[0]),
            fmt_f(c.target[1]),
            fmt_f(c.target[2])
        ));
        out.push_str(&format!("yaw = {}\n", fmt_f(c.yaw)));
        out.push_str(&format!("pitch = {}\n", fmt_f(c.pitch)));
        out.push_str(&format!("distance = {}\n\n", fmt_f(c.distance)));
    }

    if let Some(t) = &map {
        out.push_str("[map]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string(t)));
    }
    if !poses.is_empty() {
        out.push_str("[poses]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&poses)));
        if let Some((color, _)) = first_color_scale(&poses, scene) {
            out.push_str("[arrow]\n");
            out.push_str("length = 0.5\nshaft_radius = 0.025\nhead_radius = 0.06\n");
            out.push_str(&format!("color = {}\n\n", fmt_rgb(color)));
        }
        if poses.len() > 1 {
            for t in &poses {
                if let Some((color, scale, head_radius, shaft_radius)) =
                    entity_style_for_topic(t, scene)
                {
                    out.push_str(&format!("[poses.style.{}]\n", toml_string(t)));
                    out.push_str(&format!("length = {}\n", fmt_f(scale.unwrap_or(0.5))));
                    out.push_str(&format!(
                        "shaft_radius = {}\n",
                        fmt_f(shaft_radius.unwrap_or(0.025))
                    ));
                    out.push_str(&format!(
                        "head_radius = {}\n",
                        fmt_f(head_radius.unwrap_or(0.06))
                    ));
                    out.push_str(&format!("color = {}\n\n", fmt_rgb(color)));
                }
            }
        }
    }
    if !pose_arrays.is_empty() {
        out.push_str("[pose_arrays]\n");
        out.push_str(&format!(
            "topics = [{}]\n\n",
            toml_string_list(&pose_arrays)
        ));
        if pose_arrays.len() > 1 {
            for t in &pose_arrays {
                if let Some((color, scale, head_radius, shaft_radius)) =
                    entity_style_for_topic(t, scene)
                {
                    out.push_str(&format!("[pose_arrays.style.{}]\n", toml_string(t)));
                    out.push_str(&format!("length = {}\n", fmt_f(scale.unwrap_or(0.5))));
                    out.push_str(&format!(
                        "shaft_radius = {}\n",
                        fmt_f(shaft_radius.unwrap_or(0.025))
                    ));
                    out.push_str(&format!(
                        "head_radius = {}\n",
                        fmt_f(head_radius.unwrap_or(0.06))
                    ));
                    out.push_str(&format!("color = {}\n\n", fmt_rgb(color)));
                }
            }
        }
    }
    if !paths.is_empty() {
        out.push_str("[paths]\n");
        out.push_str(&format!("topics = [{}]\n", toml_string_list(&paths)));
        // A bare `style = {...}` and per-topic `[paths.style."<topic>"]` blocks
        // share the same TOML key, so they're mutually exclusive per file.
        if paths.len() <= 1 {
            if let Some((color, scale)) = first_color_scale(&paths, scene) {
                out.push_str(&format!(
                    "style = {{ width = {}, color = {} }}\n",
                    fmt_f(scale.unwrap_or(2.0)),
                    fmt_rgb(color)
                ));
            }
        }
        out.push('\n');
        if paths.len() > 1 {
            for t in &paths {
                if let Some((color, scale, _, _)) = entity_style_for_topic(t, scene) {
                    out.push_str(&format!("[paths.style.{}]\n", toml_string(t)));
                    out.push_str(&format!("width = {}\n", fmt_f(scale.unwrap_or(0.05))));
                    out.push_str(&format!("color = {}\n\n", fmt_rgb(color)));
                }
            }
        }
    }
    if !scans.is_empty() {
        out.push_str("[scans]\n");
        out.push_str(&format!("topics = [{}]\n", toml_string_list(&scans)));
        if scans.len() <= 1 {
            if let Some((color, scale)) = first_color_scale(&scans, scene) {
                out.push_str(&format!(
                    "style = {{ size = {}, color = {} }}\n",
                    fmt_f(scale.unwrap_or(4.0)),
                    fmt_rgb(color)
                ));
            }
        }
        out.push('\n');
        if scans.len() > 1 {
            for t in &scans {
                if let Some((color, scale, _, _)) = entity_style_for_topic(t, scene) {
                    out.push_str(&format!("[scans.style.{}]\n", toml_string(t)));
                    out.push_str(&format!("size = {}\n", fmt_f(scale.unwrap_or(4.0))));
                    out.push_str(&format!("color = {}\n\n", fmt_rgb(color)));
                }
            }
        }
    }
    if !points.is_empty() {
        out.push_str("[points]\n");
        out.push_str(&format!("topics = [{}]\n", toml_string_list(&points)));
        if points.len() <= 1 {
            if let Some((color, scale)) = first_color_scale(&points, scene) {
                out.push_str(&format!(
                    "style = {{ size = {}, color = {} }}\n",
                    fmt_f(scale.unwrap_or(2.0)),
                    fmt_rgb(color)
                ));
            }
        }
        out.push('\n');
        if points.len() > 1 {
            for t in &points {
                if let Some((color, scale, _, _)) = entity_style_for_topic(t, scene) {
                    out.push_str(&format!("[points.style.{}]\n", toml_string(t)));
                    if let Some(scale) = scale {
                        out.push_str(&format!("size = {}\n", fmt_f(scale)));
                    }
                    out.push_str(&format!("color = {}\n\n", fmt_rgb(color)));
                }
            }
        }
    }
    if !markers.is_empty() {
        out.push_str("[markers]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&markers)));
    }
    if !marker_arrays.is_empty() {
        out.push_str("[marker_arrays]\n");
        out.push_str(&format!(
            "topics = [{}]\n\n",
            toml_string_list(&marker_arrays)
        ));
    }

    for g in ui_groups {
        out.push_str("[[ui.group]]\n");
        out.push_str(&format!("name = {}\n", toml_string(&g.name)));
        if !g.topics.is_empty() {
            out.push_str(&format!(
                "topics = [{}]\n",
                toml_string_list(&g.topics)
            ));
        }
        if g.urdf {
            out.push_str("urdf = true\n");
        }
        if g.tf {
            out.push_str("tf = true\n");
        }
        if g.collapsed {
            out.push_str("collapsed = true\n");
        }
        out.push('\n');
    }

    out
}

/// Look up the first entity in `scene` whose label-token matches one of
/// `topics` and return its (color, scale). Used to bake the live-view style
/// into per-kind TOML sections.
fn first_color_scale(
    topics: &[String],
    scene: &SceneGraph,
) -> Option<(scene::Color, Option<f32>)> {
    for t in topics {
        for entity in scene.entities.values() {
            let label_token = entity
                .label
                .as_deref()
                .unwrap_or("")
                .split_whitespace()
                .next()
                .unwrap_or("");
            if label_token != t {
                continue;
            }
            if let Some(c) = scene::primitive_color(&entity.primitive) {
                return Some((c, scene::primitive_scale(&entity.primitive)));
            }
        }
    }
    None
}

/// `(color, scale, head_radius, shaft_radius)` — the last two are `None` for
/// anything but Arrows.
type EntityStyle = (scene::Color, Option<f32>, Option<f32>, Option<f32>);

/// Live style of the entity matching `topic` exactly (by label token), if any.
fn entity_style_for_topic(topic: &str, scene: &SceneGraph) -> Option<EntityStyle> {
    for entity in scene.entities.values() {
        let label_token = entity
            .label
            .as_deref()
            .unwrap_or("")
            .split_whitespace()
            .next()
            .unwrap_or("");
        if label_token != topic {
            continue;
        }
        let color = scene::primitive_color(&entity.primitive)?;
        return Some((
            color,
            scene::primitive_scale(&entity.primitive),
            scene::primitive_head_radius(&entity.primitive),
            scene::primitive_shaft_radius(&entity.primitive),
        ));
    }
    None
}

fn fmt_rgb(c: scene::Color) -> String {
    format!("[{}, {}, {}]", fmt_f(c.r), fmt_f(c.g), fmt_f(c.b))
}

fn fmt_f(v: f32) -> String {
    // Avoid `5` (integer-looking) for floats; TOML accepts both but a trailing
    // `.0` keeps the file diff-friendly.
    if v.fract() == 0.0 {
        format!("{v:.1}")
    } else {
        format!("{v}")
    }
}

fn toml_string(s: &str) -> String {
    // TOML basic-string escaping. Topic names never contain quotes or
    // backslashes in practice, but be defensive.
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

fn toml_string_list(items: &[String]) -> String {
    items
        .iter()
        .map(|s| toml_string(s))
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn snap(items: &[(&str, &[&str])]) -> Vec<(String, Vec<String>)> {
        items
            .iter()
            .map(|(t, tys)| {
                (
                    t.to_string(),
                    tys.iter().map(|s| s.to_string()).collect(),
                )
            })
            .collect()
    }

    #[test]
    fn selected_topics_routed_into_correct_sections() {
        let s = snap(&[
            ("/map", &[occupancy::MSG_TYPE]),
            ("/scan", &[laserscan::MSG_TYPE]),
            ("/plan", &[path::MSG_TYPE]),
            ("/goal_pose", &[pose::STAMPED_TYPE]),
            ("/particle_cloud", &[pose::ARRAY_TYPE]),
            ("/camera/points", &[pointcloud::MSG_TYPE]),
            ("/ignored", &["weird_msgs/msg/Thing"]),
        ]);
        let selected: Vec<String> = s.iter().map(|(t, _)| t.clone()).collect();
        let out = to_toml(&s, &selected, "map");
        assert!(out.contains("reference_frame = \"map\""));
        assert!(out.contains("[map]"));
        assert!(out.contains("\"/map\""));
        assert!(out.contains("[scans]"));
        assert!(out.contains("\"/scan\""));
        assert!(out.contains("[paths]"));
        assert!(out.contains("\"/plan\""));
        assert!(out.contains("[poses]"));
        assert!(out.contains("\"/goal_pose\""));
        assert!(out.contains("[pose_arrays]"));
        assert!(out.contains("\"/particle_cloud\""));
        assert!(out.contains("[points]"));
        assert!(out.contains("\"/camera/points\""));
        assert!(!out.contains("/ignored"));
    }

    #[test]
    fn full_config_with_view_round_trips_through_parser() {
        let s = snap(&[("/scan", &[laserscan::MSG_TYPE])]);
        let scene = SceneGraph::new("map");
        let cam = CameraSave {
            target: [1.0, 2.0, 3.0],
            yaw: 0.5,
            pitch: 0.7,
            distance: 12.0,
        };
        let out = to_toml_full(
            &s,
            &["/scan".to_string()],
            "map",
            &scene,
            0.3,
            &[],
            Some(cam),
        );
        assert!(out.contains("[view]"));
        assert!(out.contains("target = [1.0, 2.0, 3.0]"));
        // The generated file must be valid fastviz config.
        let raw: crate::config::RawConfig = toml::from_str(&out).expect("parses");
        let cfg = raw.into_runtime();
        let v = cfg.view.expect("view present");
        assert_eq!(v.target, [1.0, 2.0, 3.0]);
        assert_eq!(cfg.scan_topics, vec!["/scan"]);
    }

    #[test]
    fn unselected_topics_are_dropped() {
        let s = snap(&[
            ("/scan_front", &[laserscan::MSG_TYPE]),
            ("/scan_back", &[laserscan::MSG_TYPE]),
        ]);
        let out = to_toml(&s, &["/scan_front".to_string()], "map");
        assert!(out.contains("/scan_front"));
        assert!(!out.contains("/scan_back"));
    }

    fn path_entity(id: u64, label: &str, color: scene::Color, width: f32) -> scene::SceneEntity {
        scene::SceneEntity::new(
            scene::EntityId(id),
            scene::ScenePrimitive::Polyline(scene::Polyline {
                points: Vec::new(),
                color,
                width,
                strip: true,
            }),
        )
        .with_label(label)
    }

    #[test]
    fn multi_topic_paths_emit_distinct_per_topic_style_blocks() {
        let s = snap(&[
            ("/plan", &[path::MSG_TYPE]),
            ("/global_plan", &[path::MSG_TYPE]),
        ]);
        let mut scene = SceneGraph::new("map");
        scene.upsert(path_entity(
            1,
            "/plan",
            scene::Color::rgb(1.0, 0.0, 0.0),
            0.05,
        ));
        scene.upsert(path_entity(
            2,
            "/global_plan",
            scene::Color::rgb(0.0, 0.0, 1.0),
            0.05,
        ));
        let selected: Vec<String> = s.iter().map(|(t, _)| t.clone()).collect();
        let out = to_toml_full(&s, &selected, "map", &scene, 0.3, &[], None);
        assert!(out.contains("[paths.style.\"/plan\"]"));
        assert!(out.contains("[paths.style.\"/global_plan\"]"));
        assert!(!out.contains("style = {"));

        let raw: crate::config::RawConfig = toml::from_str(&out).expect("parses");
        let cfg = raw.into_runtime();
        let a = cfg.path_style_for("/plan");
        let b = cfg.path_style_for("/global_plan");
        assert_ne!(a.color, b.color);
        assert_eq!(a.color, scene::Color::rgb(1.0, 0.0, 0.0));
        assert_eq!(b.color, scene::Color::rgb(0.0, 0.0, 1.0));
    }

    #[test]
    fn single_topic_path_emits_no_per_topic_style_block() {
        let s = snap(&[("/plan", &[path::MSG_TYPE])]);
        let mut scene = SceneGraph::new("map");
        scene.upsert(path_entity(
            1,
            "/plan",
            scene::Color::rgb(1.0, 0.0, 0.0),
            0.05,
        ));
        let out = to_toml_full(
            &s,
            &["/plan".to_string()],
            "map",
            &scene,
            0.3,
            &[],
            None,
        );
        assert!(!out.contains("[paths.style."));
    }
}
