//! Generate a fastviz TOML config from a set of selected topics.
//!
//! The UI's topic discoverer uses this to materialise the user's checkbox
//! selection into a runnable `--config` file. Topics whose message types
//! fastviz does not understand are silently dropped.

use crate::subscribers::{laserscan, occupancy, path, pointcloud, pose};

/// Top-level kinds the writer can emit. Anything not in this set is ignored.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum TopicKind {
    Map,
    Pose,
    PoseArray,
    Path,
    Scan,
    PointCloud,
}

impl TopicKind {
    /// First supported kind that matches one of `types`.
    pub fn from_types(types: &[String]) -> Option<Self> {
        types.iter().find_map(|t| Self::from_type(t))
    }

    pub fn from_type(ty: &str) -> Option<Self> {
        match ty {
            occupancy::MSG_TYPE => Some(Self::Map),
            pose::STAMPED_TYPE => Some(Self::Pose),
            pose::ARRAY_TYPE => Some(Self::PoseArray),
            path::MSG_TYPE => Some(Self::Path),
            laserscan::MSG_TYPE => Some(Self::Scan),
            pointcloud::MSG_TYPE => Some(Self::PointCloud),
            _ => None,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::Map => "OccupancyGrid",
            Self::Pose => "PoseStamped",
            Self::PoseArray => "PoseArray",
            Self::Path => "Path",
            Self::Scan => "LaserScan",
            Self::PointCloud => "PointCloud2",
        }
    }
}

/// Render selected topics into a fastviz TOML config string.
///
/// `topics` is the (topic, types) snapshot. `selected` lists the topic names
/// the user checked. Topics whose message type isn't supported are skipped.
/// `reference_frame` is written verbatim as the file's `reference_frame`.
pub fn to_toml(
    topics: &[(String, Vec<String>)],
    selected: &[String],
    reference_frame: &str,
) -> String {
    use std::collections::BTreeSet;
    let want: BTreeSet<&str> = selected.iter().map(String::as_str).collect();

    let mut map: Option<String> = None;
    let mut poses: Vec<String> = Vec::new();
    let mut pose_arrays: Vec<String> = Vec::new();
    let mut paths: Vec<String> = Vec::new();
    let mut scans: Vec<String> = Vec::new();
    let mut points: Vec<String> = Vec::new();

    for (topic, types) in topics {
        if !want.contains(topic.as_str()) {
            continue;
        }
        match TopicKind::from_types(types) {
            Some(TopicKind::Map) => {
                // First selected map wins — fastviz only displays one.
                if map.is_none() {
                    map = Some(topic.clone());
                }
            }
            Some(TopicKind::Pose) => poses.push(topic.clone()),
            Some(TopicKind::PoseArray) => pose_arrays.push(topic.clone()),
            Some(TopicKind::Path) => paths.push(topic.clone()),
            Some(TopicKind::Scan) => scans.push(topic.clone()),
            Some(TopicKind::PointCloud) => points.push(topic.clone()),
            None => {}
        }
    }

    let mut out = String::new();
    out.push_str("# fastviz config — generated by the topic discoverer.\n");
    out.push_str(&format!("reference_frame = \"{reference_frame}\"\n\n"));

    if let Some(t) = &map {
        out.push_str("[map]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string(t)));
    }
    if !poses.is_empty() {
        out.push_str("[poses]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&poses)));
    }
    if !pose_arrays.is_empty() {
        out.push_str("[pose_arrays]\n");
        out.push_str(&format!(
            "topics = [{}]\n\n",
            toml_string_list(&pose_arrays)
        ));
    }
    if !paths.is_empty() {
        out.push_str("[paths]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&paths)));
    }
    if !scans.is_empty() {
        out.push_str("[scans]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&scans)));
    }
    if !points.is_empty() {
        out.push_str("[points]\n");
        out.push_str(&format!("topics = [{}]\n\n", toml_string_list(&points)));
    }
    out
}

fn toml_string(s: &str) -> String {
    // TOML basic-string escaping. Topic names never contain quotes or
    // backslashes in practice, but be defensive.
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

fn toml_string_list(items: &[String]) -> String {
    items
        .iter()
        .map(|s| toml_string(s))
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn snap(items: &[(&str, &[&str])]) -> Vec<(String, Vec<String>)> {
        items
            .iter()
            .map(|(t, tys)| {
                (
                    t.to_string(),
                    tys.iter().map(|s| s.to_string()).collect(),
                )
            })
            .collect()
    }

    #[test]
    fn selected_topics_routed_into_correct_sections() {
        let s = snap(&[
            ("/map", &[occupancy::MSG_TYPE]),
            ("/scan", &[laserscan::MSG_TYPE]),
            ("/plan", &[path::MSG_TYPE]),
            ("/goal_pose", &[pose::STAMPED_TYPE]),
            ("/particle_cloud", &[pose::ARRAY_TYPE]),
            ("/camera/points", &[pointcloud::MSG_TYPE]),
            ("/ignored", &["weird_msgs/msg/Thing"]),
        ]);
        let selected: Vec<String> = s.iter().map(|(t, _)| t.clone()).collect();
        let out = to_toml(&s, &selected, "map");
        assert!(out.contains("reference_frame = \"map\""));
        assert!(out.contains("[map]"));
        assert!(out.contains("\"/map\""));
        assert!(out.contains("[scans]"));
        assert!(out.contains("\"/scan\""));
        assert!(out.contains("[paths]"));
        assert!(out.contains("\"/plan\""));
        assert!(out.contains("[poses]"));
        assert!(out.contains("\"/goal_pose\""));
        assert!(out.contains("[pose_arrays]"));
        assert!(out.contains("\"/particle_cloud\""));
        assert!(out.contains("[points]"));
        assert!(out.contains("\"/camera/points\""));
        assert!(!out.contains("/ignored"));
    }

    #[test]
    fn unselected_topics_are_dropped() {
        let s = snap(&[
            ("/scan_front", &[laserscan::MSG_TYPE]),
            ("/scan_back", &[laserscan::MSG_TYPE]),
        ]);
        let out = to_toml(&s, &["/scan_front".to_string()], "map");
        assert!(out.contains("/scan_front"));
        assert!(!out.contains("/scan_back"));
    }
}
